name: Deploy Laravel ke Jagoan Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps          # 👈 use ftps instead of ftp
          port: 21                # usually still 21 for FTPS
          timeout: 60000          # increase timeout
          exclude: |
            node_modules/**
            .git/**
            .github/**
            README.md
            .env
